// GENERATED by @edgedb/generate v0.5.4

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _default from "./default";
import type * as _extauth from "./ext/auth";
export type $current_userλShape = $.typeutil.flatten<Omit<_default.$UserλShape, "identity"> & {
  "identity": $.LinkDesc<_extauth.$Identity, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $current_user = $.ObjectType<"__default::current_user", $current_userλShape, null, [
  ..._default.$User['__exclusives__'],
]>;
const $current_user = $.makeType<$current_user>(_.spec, "01e29027-66b3-11ef-979e-3d1a8dc2994e", _.syntax.literal);

const current_user: $.$expr_PathNode<$.TypeSet<$current_user, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($current_user, $.Cardinality.Many), null);



export { $current_user, current_user };

type __defaultExports = {
  "current_user": typeof current_user
};
const __defaultExports: __defaultExports = {
  "current_user": current_user
};
export default __defaultExports;
