// GENERATED by @edgedb/generate v0.5.4

import * as $ from "../reflection";
import * as _ from "../imports";
import _module__ai from "./ext/ai";
import _module__auth from "./ext/auth";
import _module__pgvector from "./ext/pgvector";
import _module__pgcrypto from "./ext/pgcrypto";


type __defaultExports = {
  "ai": typeof _module__ai;
  "auth": typeof _module__auth;
  "pgvector": typeof _module__pgvector;
  "pgcrypto": typeof _module__pgcrypto
};
const __defaultExports: __defaultExports = {
  "ai": _module__ai,
  "auth": _module__auth,
  "pgvector": _module__pgvector,
  "pgcrypto": _module__pgcrypto
};
export default __defaultExports;
