// GENERATED by @edgedb/generate v0.5.4

import * as _ from '../imports'
import * as $ from '../reflection'

import type * as ___default from './_default_10'
import type * as _extauth from './ext/auth'
import type * as _std from './std'

export type $UserλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  'identity': $.LinkDesc<_extauth.$Identity, $.Cardinality.One, {}, false, false, false, false>
  'name': $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>
  'posts': $.LinkDesc<$Blogpost, $.Cardinality.Many, {}, false, false, false, false>
  '<author[is Blogpost]': $.LinkDesc<$Blogpost, $.Cardinality.Many, {}, false, false, false, false>
  '<author': $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false, false, false>
}>
type $User = $.ObjectType<'default::User', $UserλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>
const $User = $.makeType<$User>(_.spec, '52be200e-5bb5-11ef-ad14-511b89c9d392', _.syntax.literal)

const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null)

export type $BlogpostλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  'author': $.LinkDesc<$User, $.Cardinality.One, {}, false, false, false, true>
  'content': $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, true>
  'description': $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, true>
  'title': $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, true>
  '<posts[is User]': $.LinkDesc<$User, $.Cardinality.Many, {}, false, false, false, false>
  '<posts[is current_user]': $.LinkDesc<$current_user, $.Cardinality.Many, {}, false, false, false, false>
  '<posts[is __default::current_user]': $.LinkDesc<___default.$current_user, $.Cardinality.Many, {}, false, false, false, false>
  '<posts': $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false, false, false>
}>
type $Blogpost = $.ObjectType<'default::Blogpost', $BlogpostλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>
const $Blogpost = $.makeType<$Blogpost>(_.spec, '52c7c8b6-5bb5-11ef-998b-75337a142212', _.syntax.literal)

const Blogpost: $.$expr_PathNode<$.TypeSet<$Blogpost, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Blogpost, $.Cardinality.Many), null)

export type $current_userλShape = $.typeutil.flatten<$UserλShape & {
}>
type $current_user = $.ObjectType<'default::current_user', $current_userλShape, null, [
  ...$User['__exclusives__'],
]>
const $current_user = $.makeType<$current_user>(_.spec, '52c7972e-5bb5-11ef-be79-b566789cc320', _.syntax.literal)

const current_user: $.$expr_PathNode<$.TypeSet<$current_user, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($current_user, $.Cardinality.Many), null)

const $default__globals: { current_user: _.syntax.$expr_Global<
  // "default::current_user",
  $current_user,
  $.Cardinality.AtMostOne
> } = { current_user: _.syntax.makeGlobal(
  'default::current_user',
  $.makeType(_.spec, '52c7972e-5bb5-11ef-be79-b566789cc320', _.syntax.literal),
  $.Cardinality.AtMostOne,
) as any }

export { $User, User, $Blogpost, Blogpost, $current_user, current_user }

type __defaultExports = {
  User: typeof User
  Blogpost: typeof Blogpost
  current_user: typeof current_user
  global: typeof $default__globals
}
const __defaultExports: __defaultExports = {
  User,
  Blogpost,
  current_user,
  global: $default__globals,
}
export default __defaultExports
