// GENERATED by @edgedb/generate v0.5.4

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _extauth from "./ext/auth";
export type $UserλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "identity": $.LinkDesc<_extauth.$Identity, $.Cardinality.One, {}, false, false,  false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<author[is Blogpost]": $.LinkDesc<$Blogpost, $.Cardinality.Many, {}, false, false,  false, false>;
  "<author": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $User = $.ObjectType<"default::User", $UserλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $User = $.makeType<$User>(_.spec, "7c95c12e-5b0c-11ef-ab87-7d699b88c6eb", _.syntax.literal);

const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);

export type $BlogpostλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "author": $.LinkDesc<$User, $.Cardinality.One, {}, false, false,  false, false>;
  "content": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, true>;
  "title": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, true>;
}>;
type $Blogpost = $.ObjectType<"default::Blogpost", $BlogpostλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Blogpost = $.makeType<$Blogpost>(_.spec, "7ca0c006-5b0c-11ef-a034-3fffa64f1e2d", _.syntax.literal);

const Blogpost: $.$expr_PathNode<$.TypeSet<$Blogpost, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Blogpost, $.Cardinality.Many), null);

export type $current_userλShape = $.typeutil.flatten<$UserλShape & {
}>;
type $current_user = $.ObjectType<"default::current_user", $current_userλShape, null, [
  ...$User['__exclusives__'],
]>;
const $current_user = $.makeType<$current_user>(_.spec, "7ca087f6-5b0c-11ef-a57b-8909900368e2", _.syntax.literal);

const current_user: $.$expr_PathNode<$.TypeSet<$current_user, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($current_user, $.Cardinality.Many), null);

const $default__globals: {  current_user: _.syntax.$expr_Global<
              // "default::current_user",
              $current_user,
              $.Cardinality.AtMostOne
              >} = {  current_user: _.syntax.makeGlobal(
              "default::current_user",
              $.makeType(_.spec, "7ca087f6-5b0c-11ef-a57b-8909900368e2", _.syntax.literal),
              $.Cardinality.AtMostOne) as any};



export { $User, User, $Blogpost, Blogpost, $current_user, current_user };

type __defaultExports = {
  "User": typeof User;
  "Blogpost": typeof Blogpost;
  "current_user": typeof current_user;
  "global": typeof $default__globals
};
const __defaultExports: __defaultExports = {
  "User": User,
  "Blogpost": Blogpost,
  "current_user": current_user,
  "global": $default__globals
};
export default __defaultExports;
